
-- Insert Quest Templates
INSERT INTO quest_template (description, difficulty, type, tags, xp) VALUES
('Find a red flower growing through concrete', 'Easy', 'Solo', 'exploration,nature', 100),
('Take a picture of a street art mural', 'Easy', 'Solo', 'exploration,art', 100),
('Visit a park you have never been to', 'Medium', 'Solo', 'exploration,outdoors', 100),
('Find a building with a clock tower', 'Easy', 'Solo', 'exploration,urban', 100),
('Spot a bird building a nest', 'Medium', 'Solo', 'exploration,nature', 100),
('Find a statue of a person', 'Easy', 'Solo', 'exploration,history', 100),
('Locate a public fountain', 'Easy', 'Solo', 'exploration,urban', 100),
('Find a tree that looks older than 100 years', 'Medium', 'Solo', 'exploration,nature', 100),
('Discover a hidden alleyway', 'Medium', 'Solo', 'exploration,urban', 100),
('Find a place with a great view of the sunset', 'Medium', 'Solo', 'exploration,nature', 100),
('Locate a library', 'Easy', 'Solo', 'exploration,knowledge', 100),
('Find a local bakery', 'Easy', 'Solo', 'exploration,food', 100),
('Spot a classic car', 'Hard', 'Solo', 'exploration,cars', 100),
('Find a neon sign', 'Medium', 'Solo', 'exploration,urban', 100),
('Locate a bridge', 'Easy', 'Solo', 'exploration,urban', 100),
('Find a body of water (pond, river, lake)', 'Medium', 'Solo', 'exploration,nature', 100),
('Spot a squirrel', 'Easy', 'Solo', 'exploration,nature', 100),
('Find a bench with a dedication plaque', 'Medium', 'Solo', 'exploration,history', 100),
('Locate a post office', 'Easy', 'Solo', 'exploration,urban', 100),
('Find a street musician', 'Hard', 'Solo', 'exploration,music', 100),
('Compliment a stranger on their outfit', 'Medium', 'Solo', 'social,kindness', 100),
('Hold the door open for someone', 'Easy', 'Solo', 'social,kindness', 100),
('Call a friend you haven''t spoken to in a while', 'Medium', 'Solo', 'social,connection', 100),
('Ask a barista for their recommendation', 'Easy', 'Solo', 'social,interaction', 100),
('High-five a friend', 'Easy', 'Solo', 'social,fun', 100),
('Write a thank you note to someone', 'Medium', 'Solo', 'social,gratitude', 100),
('Smile at 5 strangers', 'Medium', 'Solo', 'social,kindness', 100),
('Ask someone for directions (even if you know the way)', 'Hard', 'Solo', 'social,courage', 100),
('Pay for the person behind you in line', 'Hard', 'Solo', 'social,generosity', 100),
('Leave a nice comment on a social media post', 'Easy', 'Solo', 'social,digital', 100),
('Send a funny meme to a family member', 'Easy', 'Solo', 'social,connection', 100),
('Introduce yourself to a neighbor', 'Hard', 'Solo', 'social,community', 100),
('Give a genuine compliment to a coworker/classmate', 'Medium', 'Solo', 'social,kindness', 100),
('Ask an elder about their favorite memory', 'Medium', 'Solo', 'social,wisdom', 100),
('Make someone laugh', 'Medium', 'Solo', 'social,fun', 100),
('Help someone carry something heavy', 'Medium', 'Solo', 'social,kindness', 100),
('Recommend a song to a friend', 'Easy', 'Solo', 'social,music', 100),
('Wave at a baby', 'Easy', 'Solo', 'social,fun', 100),
('Say "Good Morning" to 3 people', 'Easy', 'Solo', 'social,politeness', 100),
('Listen to someone without interrupting', 'Medium', 'Solo', 'social,patience', 100),
('Do 10 pushups', 'Easy', 'Solo', 'fitness,strength', 100),
('Walk 5,000 steps', 'Medium', 'Solo', 'fitness,cardio', 100),
('Hold a plank for 1 minute', 'Medium', 'Solo', 'fitness,core', 100),
('Take the stairs instead of the elevator', 'Easy', 'Solo', 'fitness,habit', 100),
('Stretch for 10 minutes', 'Easy', 'Solo', 'fitness,flexibility', 100),
('Go for a 15-minute jog', 'Medium', 'Solo', 'fitness,cardio', 100),
('Do 20 jumping jacks', 'Easy', 'Solo', 'fitness,cardio', 100),
('Drink 2 liters of water', 'Easy', 'Solo', 'fitness,health', 100),
('Eat a piece of fruit', 'Easy', 'Solo', 'fitness,nutrition', 100),
('Do 10 squats', 'Easy', 'Solo', 'fitness,strength', 100),
('Balance on one leg for 1 minute', 'Medium', 'Solo', 'fitness,balance', 100),
('Do a handstand (against a wall is okay)', 'Hard', 'Solo', 'fitness,skill', 100),
('Walk backwards for 1 minute', 'Easy', 'Solo', 'fitness,fun', 100),
('Skip rope for 2 minutes', 'Hard', 'Solo', 'fitness,cardio', 100),
('Do 5 lunges on each leg', 'Easy', 'Solo', 'fitness,strength', 100),
('Touch your toes', 'Easy', 'Solo', 'fitness,flexibility', 100),
('Go for a bike ride', 'Medium', 'Solo', 'fitness,cardio', 100),
('Dance to your favorite song', 'Easy', 'Solo', 'fitness,fun', 100),
('Do 10 sit-ups', 'Easy', 'Solo', 'fitness,core', 100),
('Park far away and walk to the store', 'Easy', 'Solo', 'fitness,habit', 100),
('Draw a doodle of your surroundings', 'Easy', 'Solo', 'creativity,art', 100),
('Write a haiku', 'Easy', 'Solo', 'creativity,writing', 100),
('Take a photo of something blue', 'Easy', 'Solo', 'creativity,photography', 100),
('Make a paper airplane', 'Easy', 'Solo', 'creativity,craft', 100),
('Cook a new recipe', 'Medium', 'Solo', 'creativity,cooking', 100),
('Write a short poem about coffee', 'Easy', 'Solo', 'creativity,writing', 100),
('Create a new playlist', 'Easy', 'Solo', 'creativity,music', 100),
('Rearrange a shelf or desk', 'Medium', 'Solo', 'creativity,design', 100),
('Learn a magic trick', 'Medium', 'Solo', 'creativity,skill', 100),
('Build a house of cards', 'Hard', 'Solo', 'creativity,skill', 100),
('Draw a self-portrait blindfolded', 'Medium', 'Solo', 'creativity,fun', 100),
('Write a letter to your future self', 'Medium', 'Solo', 'creativity,writing', 100),
('Invent a new word and define it', 'Easy', 'Solo', 'creativity,language', 100),
('Take a photo from a worm''s eye view', 'Easy', 'Solo', 'creativity,photography', 100),
('Make a collage from old magazines', 'Medium', 'Solo', 'creativity,art', 100),
('Whistle a tune', 'Easy', 'Solo', 'creativity,music', 100),
('Write a 6-word story', 'Easy', 'Solo', 'creativity,writing', 100),
('Create a secret handshake', 'Easy', 'Party', 'creativity,social', 100),
('Draw a map of your neighborhood from memory', 'Medium', 'Solo', 'creativity,memory', 100),
('Make a sock puppet', 'Medium', 'Solo', 'creativity,craft', 100),
('Meditate for 5 minutes', 'Easy', 'Solo', 'mindfulness,peace', 100),
('Watch the sunset', 'Easy', 'Solo', 'mindfulness,nature', 100),
('List 3 things you are grateful for', 'Easy', 'Solo', 'mindfulness,gratitude', 100),
('Take 10 deep breaths', 'Easy', 'Solo', 'mindfulness,calm', 100),
('Listen to the sounds of nature for 2 minutes', 'Easy', 'Solo', 'mindfulness,nature', 100),
('Eat a meal without looking at a screen', 'Medium', 'Solo', 'mindfulness,focus', 100),
('Declutter one drawer', 'Medium', 'Solo', 'mindfulness,organization', 100),
('Read a chapter of a book', 'Medium', 'Solo', 'mindfulness,reading', 100),
('Write down your dreams from last night', 'Easy', 'Solo', 'mindfulness,journaling', 100),
('Spend 10 minutes doing absolutely nothing', 'Hard', 'Solo', 'mindfulness,rest', 100),
('Observe a plant for 2 minutes', 'Easy', 'Solo', 'mindfulness,nature', 100),
('Walk barefoot on grass', 'Easy', 'Solo', 'mindfulness,grounding', 100),
('Smell a flower', 'Easy', 'Solo', 'mindfulness,senses', 100),
('Look at the stars', 'Easy', 'Solo', 'mindfulness,nature', 100),
('Journal about your day', 'Medium', 'Solo', 'mindfulness,reflection', 100),
('Turn off your phone for 1 hour', 'Hard', 'Solo', 'mindfulness,detox', 100),
('Listen to a classical music piece', 'Easy', 'Solo', 'mindfulness,music', 100),
('Notice 5 things you can see, 4 you can touch...', 'Easy', 'Solo', 'mindfulness,grounding', 100),
('Forgive someone (internally)', 'Hard', 'Solo', 'mindfulness,peace', 100),
('Say a positive affirmation', 'Easy', 'Solo', 'mindfulness,self-love', 100);
